version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # API (S3 compatible)
      - "9001:9001"   # Web console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
