server.port=${SERVER_PORT:8099}
spring.application.name=chat-service
spring.config.import=optional:file:deploy/.env.chat[.properties],optional:file:../deploy/.env.chat[.properties],optional:file:iems-backend/deploy/.env.chat[.properties]


# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:${CHAT_MONGODB_URI:mongodb://localhost:27017/iems-chat}}
spring.data.mongodb.database=${MONGODB_DATABASE:${CHAT_MONGODB_DATABASE:iems-chat}}

#spring.data.mongodb.uri=mongodb://localhost:27017
#spring.data.mongodb.database=chat-db
# WebSocket message broker tuning (optional defaults are fine)
spring.websocket.messages.simp.enabled=true

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.messaging=INFO


# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}

# Multipart size limits to forward big uploads to document-service
spring.servlet.multipart.max-file-size=60MB
spring.servlet.multipart.max-request-size=70MB
