name: Deploy Document Service

on:
  push:
    branches: [main]
    paths:
      - "document-service/**"
      - "pom.xml"
      - "mvnw"
      - ".mvn/**"
      - "deploy/compose-document-service.yml"
      - ".github/workflows/_deploy-service.yml"
      - ".github/workflows/deploy-document-service.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service: document-service
      image: document-service
      compose_file: compose-document-service.yml
      env_file: .env.document
    secrets: inherit
