name: Deploy Notification Service

on:
  push:
    branches: [main]
    paths:
      - "notification-service/**"
      - "pom.xml"
      - "mvnw"
      - ".mvn/**"
      - "deploy/compose-notification-service.yml"
      - ".github/workflows/_deploy-service.yml"
      - ".github/workflows/deploy-notification-service.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-service.yml
    with:
      service: notification-service
      image: notification-service
      compose_file: compose-notification-service.yml
      env_file: .env.notification
    secrets: inherit
